# permissions for end users to edit composableresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: composable-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: composableresource-editor-role
rules:
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composableresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composableresources/status
  verbs:
  - get
