---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - credentials
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests
  - composableresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests/finalizers
  - composableresources/finalizers
  verbs:
  - update
- apiGroups:
  - cro.hpsys.ibm.ie.com
  resources:
  - composabilityrequests/status
  - composableresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - machines/status
  verbs:
  - get
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceslices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceslices/status
  verbs:
  - get
  - patch
  - update
