apiVersion: cro.hpsys.ibm.ie.com/v1alpha1
kind: ComposabilityRequest
metadata:
  name: composabilityrequest-sample
spec:
  resource:
    type: "gpu"
    size: 2
    model: "NVIDIA-A100-PCIE-40GB"
    other_spec:
      milli_cpu: 2
      memory: 40
      ephemeral_storage: 2
      allowed_pod_number: 5
    target_node: "node1"
    force_detach: true
    allocation_policy: "samenode"
